# Generated by Django 2.2.4 on 2019-11-24 11:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=2048, null=True)),
                ('type_of_cloth', models.CharField(max_length=20, null=True)),
                ('cloth_uuid', models.UUIDField(null=True)),
            ],
        ),
    ]
