# Generated by Django 2.2.4 on 2019-11-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='belongs_to_user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
