# Generated by Django 2.2.4 on 2019-11-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersApp', '0002_order_belongs_to_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
