# Generated by Django 2.2.4 on 2019-11-24 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersApp', '0002_order_belongs_to_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='type_of_cloth',
            new_name='cloth',
        ),
    ]
