# Generated by Django 2.2.4 on 2020-10-14 04:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_of_object', models.CharField(max_length=20, null=True)),
                ('text', models.CharField(max_length=2048, null=True)),
                ('count', models.IntegerField(default=1)),
            ],
        ),
    ]
