# Generated by Django 2.2.4 on 2019-11-28 15:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryList',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_uuid', models.IntegerField(default=0)),
                ('user_id', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=2048, null=True)),
            ],
        ),
    ]
