# Generated by Django 2.2.4 on 2019-11-23 15:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_of_cloth', models.CharField(max_length=2048, null=True)),
                ('days_for_clearing', models.IntegerField()),
            ],
        ),
    ]
