# Generated by Django 2.2.4 on 2019-11-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClothsApp', '0002_auto_20191123_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='days_for_clearing',
            field=models.IntegerField(default=0),
        ),
    ]
